export const PURCHASE_REQUEST="PURCHASE_REQUST"
export const PURCHASE_SUCCESS="PURCHASE_SUCCESS"
export const PURCHASE_FAILURE="PURCHASE_FAILURE"


export const GET_PURCHASE_REQUEST="GET_PURCHASE_REQUST"
export const GET_PURCHASE_SUCCESS="GET_PURCHASE_SUCCESS"
export const GET_PURCHASE_FAILURE="GET_PURCHASE_FAILURE"


 